### ISSUE TITLE
Package does not provide core fonts

### ISSUE THREAD

**Issue by mklemarczyk** [tecnickcom/tc-lib-pdf-font#2]
Composer package does not cover core fonts like it was in the previous version.
It makes package useless. Can you prepare instruction how to create files for core fonts or include json files for them?

`$pdf->font->insert($fontPon, 'Courier', 11);`

This code is running infinite, since "fonts" dir can not be found. It should not work like this.
(Method findParentDir loops infinite, if dir can not be found.)

**Comment by mklemarczyk** [comment]
I would like to improve composer.json file to install fonts via composer in post-install-cmd stage.

What do you think about that? It will simplify installation process and should not violate any license because fonts will not be included in package anyway.

**Comment by nicolaasuni** [comment]
Core fonts are already included in:
https://github.com/tecnickcom/tc-font-mirror
that is already included in:
https://github.com/tecnickcom/tc-lib-pdf-font/blob/develop/util/composer.json#L34

**Comment by mklemarczyk** [comment]
I like to integrate it more with root composer file. Current approach is hard to use and not well documented.
I will create pull request to make you decide.
