### ISSUE TITLE
convert fonts

### ISSUE THREAD

**Issue by hmadadian** [tecnickcom/tc-lib-pdf-font#4]
@nicolaasuni
hi
I want to convert some Persian (Farsi) fonts to tcpdf format (.php, .ctg.z and .z files).
I used several methods 
1- convert it by online tools like 
A ) http://fonts.snm-portal.com
B ) http://www.xml-convert.com
the result was kinda okay but some of the characters replaced with squares and that's not good enough for us.
2- convert it by TCPDF latest version builtin tools (tcpdf_addfont.php)
the result was so bad it shows some nonsense characters like greek.
even I tried it with PHP coding and no luck either.
then I google some and see new tools for this, tc-lib-pdf-font.
I installed it and nothing got wrong during the installation but the 
`vendor/tecnickcom/tc-lib-pdf-font/util/convert.php` 
generates JSON file instead of a PHP file. I need it to be PHP file, how can I do that?

**Comment by nicolaasuni** [comment]
This converter is not compatible with the legacy TCPDF library.
The new format is only for the new tc-lib-pdf library that is not complete yet.

**Comment by hmadadian** [comment]
May I ask you what is the best way to convert Persian ttf font to TCPDF format?

**Comment by hmadadian** [comment]
> This converter is not compatible with the legacy TCPDF library.
> The new format is only for the new tc-lib-pdf library that is not complete yet.

May I ask you what is the best way to convert Persian ttf font to TCPDF format? (.z , .ctg.z and .php files)

**Comment by norbertoramirez** [comment]
lo acabo de hacer con esta pagina [https://fonts.palettize.me/](https://fonts.palettize.me/) y me funciona perfectamente con la librería TCPDF
