### ISSUE TITLE
How to add an additional font

### ISSUE THREAD

**Issue by labby** [tecnickcom/tc-lib-pdf-font#5]
Hi there
I read this https://tcpdf.org/docs/fonts/
but how new fonts (for example Lato) can now be added?

Thanks for info

**Comment by labby** [comment]
anyone?

**Comment by kentdahl** [comment]
That link is for the old TCPDF. If that is what you are using; here is what I have in my deploy script for a Laravel web application using composer:

```bash
## Fonts for TCPDF
pushd resources/fonts/RobotoCondensed
FFS=`echo \`ls -c RobotoCondensed-{Regular,Bold,Italic,BoldItalic,Light,LightItalic}.ttf\`  | sed s/\ /\,/g`
php ../../../vendor/tecnickcom/tcpdf/tools/tcpdf_addfont.php -b -t TrueTypeUnicode -f 32 -i $FFS
popd
```
No idea how the equivalent is on tc-lib-pdf-font as I haven't used it yet.

**Comment by nicolaasuni** [comment]
This is part of the new tc-lib-pdf library that is not yet complete. for TCPDF please refer to the documentation in https://tcpdf.org
