### ISSUE TITLE
Unexpected target dir when running `util/bulk_convert.php`

### ISSUE THREAD

**Issue by juho-jaakkola** [tecnickcom/tc-lib-pdf-font#9]
**Describe the bug**
The generated fonts end up in the filesystem root if the target dir given with `--outfile` option does not exist.

**To Reproduce**
Run the command with a path that does not exist:
```
php util/bulk_convert.php --outfile does/not/exist
```

**Expected behavior**
Expectation is that the code checks the existence of the directory and creates it if necessary:
https://github.com/tecnickcom/tc-lib-pdf-font/blob/f5bbbfeefb648ae87e6b9ed267cdab45c76052da/util/bulk_convert.php#L80-L83

However this code here messes it up:
https://github.com/tecnickcom/tc-lib-pdf-font/blob/f5bbbfeefb648ae87e6b9ed267cdab45c76052da/util/bulk_convert.php#L67-L70

First `realpath($val)` returns `false` for the nonexistent path, and after that `/` gets appended to `false`, which effectively results in the target path being just `/`, as in the filesystem root.

**Comment by nicolaasuni** [comment]
There is no "--outfile" argument for the bulk_convert.php script.
The correct argument is "outpath".
